#!/bin/bash

# Run test first
./script/test

build_dir="build"
example_dir="example"
entry_point="index.js"
target_point="wlp-timeline"

# Delete example/build dir
rm -rf $example_dir/$build_dir

# Create a build folder
mkdir $example_dir/$build_dir/

cp src/css/wlp-timeline.css $build_dir/wlp-timeline.css
cp src/resources/* $build_dir/
rollup -c -f umd -n wlp_timeline -o $build_dir/$target_point.js -- $entry_point

cp src/css/wlp-timeline.css $example_dir/$build_dir/wlp-timeline.css
cp src/resources/* $example_dir/$build_dir/
rollup -c $1 -f umd -n wlp_timeline -o $example_dir/$build_dir/$target_point.js -- $entry_point

# uglify seems to not work so well with es6 code
# uglifyjs $build_dir/$target_point.js -c negate_iife=false -m -o $build_dir/$target_point.min.js
